// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRv9_WJVaPRIV40apxhQbl0CUHSWLV2cs',
    appId: '1:883617724709:web:4a38223cd0abff5beb42cc',
    messagingSenderId: '883617724709',
    projectId: 'pdaware',
    authDomain: 'pdaware.firebaseapp.com',
    storageBucket: 'pdaware.appspot.com',
    measurementId: 'G-GTLCSDXNCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI237XzHD47OdsfV6gvWuo2IF1rxdhhDg',
    appId: '1:883617724709:android:d3a5c0ac3c60651eeb42cc',
    messagingSenderId: '883617724709',
    projectId: 'pdaware',
    storageBucket: 'pdaware.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAkC7kOWkLdlyE4IQ8zus1BbF4kDiSw9U',
    appId: '1:883617724709:ios:125c6b34ba4a2d37eb42cc',
    messagingSenderId: '883617724709',
    projectId: 'pdaware',
    storageBucket: 'pdaware.appspot.com',
    androidClientId: '883617724709-ei76dgh30qs2s52jcu43gipoc4j6sllk.apps.googleusercontent.com',
    iosClientId: '883617724709-n7i77ppv5sgp0m8vghtt1s0uonpkhits.apps.googleusercontent.com',
    iosBundleId: 'org.echowear.ezpd',
  );
}

